# Generated by Django 6.0.1 on 2026-02-23 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='(Obligatorio)', max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('username', models.CharField(help_text='(Obligatorio)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Es super usuario?')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha creación')),
                ('notification_token', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Token de notificación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InfoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(help_text='(Obligatorio)', verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, help_text='(Opcional)', max_length=11, null=True, verbose_name='Teléfono')),
                ('country', models.CharField(choices=[('ES', 'ESPAÑA'), ('FR', 'FRANCIA'), ('DE', 'ALEMANIA'), ('UK', 'REINO UNIDO'), ('IT', 'ITALIA'), ('PT', 'PORTUGAL'), ('US', 'ESTADOS UNIDOS'), ('CA', 'CANADÁ'), ('BR', 'BRASIL'), ('MX', 'MÉXICO'), ('AR', 'ARGENTINA'), ('JP', 'JAPÓN'), ('CN', 'CHINA'), ('AU', 'AUSTRALIA')], default='ES', help_text='(Obligatorio)', max_length=3, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info perfil',
                'verbose_name_plural': 'Datos del perfil',
                'db_table': 'info_perfil',
                'ordering': ('-country',),
            },
        ),
    ]
