# Generated by Django 6.0.2 on 2026-05-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoperfil',
            name='birthday',
            field=models.DateField(blank=True, help_text='(Opcional)', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
