# Generated by Django 6.0.2 on 2026-02-17 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='InfoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(help_text='(Obligatorio)', verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, help_text='(Opcional)', max_length=11, null=True, verbose_name='Teléfono')),
                ('country', models.CharField(choices=[('ES', 'ESPAÑA'), ('FR', 'FRANCIA'), ('DE', 'ALEMANIA'), ('UK', 'REINO UNIDO'), ('IT', 'ITALIA'), ('PT', 'PORTUGAL'), ('US', 'ESTADOS UNIDOS'), ('CA', 'CANADÁ'), ('BR', 'BRASIL'), ('MX', 'MÉXICO'), ('AR', 'ARGENTINA'), ('JP', 'JAPÓN'), ('CN', 'CHINA'), ('AU', 'AUSTRALIA')], default='ES', help_text='(Obligatorio)', max_length=3, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info perfil',
                'verbose_name_plural': 'Datos del perfil',
                'db_table': 'info_perfil',
                'ordering': ('-country',),
            },
        ),
    ]
