# Generated by Django 6.0.2 on 2026-05-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_infoperfil_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoperfil',
            name='country',
            field=models.CharField(blank=True, choices=[('ES', 'ESPAÑA'), ('FR', 'FRANCIA'), ('DE', 'ALEMANIA'), ('UK', 'REINO UNIDO'), ('IT', 'ITALIA'), ('PT', 'PORTUGAL'), ('US', 'ESTADOS UNIDOS'), ('CA', 'CANADÁ'), ('BR', 'BRASIL'), ('MX', 'MÉXICO'), ('AR', 'ARGENTINA'), ('JP', 'JAPÓN'), ('CN', 'CHINA'), ('AU', 'AUSTRALIA')], default='ES', help_text='(Opcional)', max_length=3, null=True, verbose_name='País'),
        ),
    ]
