# Generated by Django 6.0.2 on 2026-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_last_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='infoperfil',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha creación'),
        ),
    ]
