# Generated by Django 6.0.2 on 2026-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_first_name_user_name_infoperfil_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='infoperfil',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha creación'),
        ),
    ]
