# Generated by Django 6.0.2 on 2026-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_options_remove_infoperfil_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Token de notificación'),
        ),
    ]
