# Generated by Django 6.0.1 on 2026-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('match_name', models.CharField(max_length=100)),
                ('league_name', models.CharField(max_length=150)),
                ('tournament_name', models.CharField(max_length=150)),
                ('serie_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('videogame_name', models.CharField(max_length=100)),
                ('opponents', models.JSONField(blank=True, default=list)),
                ('match_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_games', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('results', models.JSONField(blank=True, default=list)),
                ('winner_id', models.IntegerField(blank=True, null=True)),
                ('streams', models.JSONField(blank=True, default=list)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
