# Generated by Django 6.0.2 on 2026-02-23 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preferences', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferencia',
            options={'ordering': ['-puntaje_interes', '-frecuencia']},
        ),
        migrations.RenameField(
            model_name='preferencia',
            old_name='total_suscripciones',
            new_name='frecuencia',
        ),
        migrations.AddField(
            model_name='preferencia',
            name='tipo_preferencia',
            field=models.CharField(choices=[('videojuego', 'Videojuego'), ('jugador', 'Jugador/Equipo'), ('liga', 'Liga'), ('torneo', 'Torneo')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencia',
            name='valor',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencia',
            name='total_suscripciones_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferencia',
            name='valor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='preferencia',
            unique_together={('usuario', 'tipo_preferencia', 'valor')},
        ),
        migrations.RemoveField(
            model_name='preferencia',
            name='player',
        ),
        migrations.RemoveField(
            model_name='preferencia',
            name='videojuego',
        ),
    ]
