# Generated by Django 6.0.2 on 2026-05-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='recordatorio_1_dia',
            new_name='recordatorio_5_minutos',
        ),
    ]
